modLoader="javafml"
loaderVersion="[28,)"
[[mods]]
	modId="uniquee"
	version="1.9.0"
	displayName="Unique Enchantments"
	credits="Thanks Xaikii for the Mod Design, Thanks to Speiger for the Code"
	authors="Speiger, Xaikii"
	description='''
	A Set of Unique Enchantments
	'''
[[mods]]
	modId="uniqueutil"
	version="1.0.0"
	displayName="Unique Util Enchantments"
	credits="Thanks Xaikii for the Mod Design, Thanks to Speiger for the Code"
	authors="Speiger, Xaikii"
	description='''
	A Set of Unique Utility Enchantments
	'''
	[[dependencies.uniqueutil]]
		modId="uniquee"
		mandatory=true
		versionRange="[1.9,)"
		ordering="BEFORE"
		side="BOTH"